/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package agendamentorecomendacoes;

/**
 *
 * @author user
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        setLocationRelativeTo( null );
        this.setSize(430,300);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btAgendar = new javax.swing.JButton();
        btGerenciar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lbStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo.setText("Agendamento de Recomendações");
        jPanel1.add(lbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 100));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btAgendar.setText("Agendar Recomendações");
        btAgendar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAgendarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btAgendarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btAgendarMouseExited(evt);
            }
        });
        btAgendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgendarActionPerformed(evt);
            }
        });
        jPanel2.add(btAgendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        btGerenciar.setText("Gerenciar Histórico");
        btGerenciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btGerenciarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btGerenciarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btGerenciarMouseExited(evt);
            }
        });
        btGerenciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerenciarActionPerformed(evt);
            }
        });
        jPanel2.add(btGerenciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 150, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 400, 100));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(lbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 400, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgendarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btAgendarActionPerformed

    private void btGerenciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerenciarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btGerenciarActionPerformed

    private void btAgendarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAgendarMouseClicked
        TelaAgendar agendamento = new TelaAgendar();
        agendamento.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btAgendarMouseClicked

    private void btGerenciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btGerenciarMouseClicked
        TelaGerenciar gerenciamento = new TelaGerenciar();
        gerenciamento.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btGerenciarMouseClicked

    private void btAgendarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAgendarMouseEntered
        lbStatus.setText("Permite o agendamento de um objeto de aprendizagem para alunos!");
    }//GEN-LAST:event_btAgendarMouseEntered

    private void btAgendarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAgendarMouseExited
       lbStatus.setText("");
    }//GEN-LAST:event_btAgendarMouseExited

    private void btGerenciarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btGerenciarMouseEntered
        lbStatus.setText("Gerencia seu histórico de recomendações!");
    }//GEN-LAST:event_btGerenciarMouseEntered

    private void btGerenciarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btGerenciarMouseExited
       lbStatus.setText("");
    }//GEN-LAST:event_btGerenciarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAgendar;
    private javax.swing.JButton btGerenciar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JLabel lbTitulo;
    // End of variables declaration//GEN-END:variables
}
