package agendamentorecomendacoes;

import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import java.util.Date;


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class TelaAgendar extends javax.swing.JFrame {

    private DefaultListModel model = new DefaultListModel();
    private String gambs;
    private ObjRecomendacao f =  null;
    private ArrayList<Aluno> alunos;
    private ArrayList<ObjRecomendacao> objetos;
    private boolean frag = false;

    /**
     * Creates new form TelaAgendar1
     */
   
     public TelaAgendar(){
        initComponents();
        setLocationRelativeTo( null );
        this.setResizable(false);
    }

    public void setGambs(String a){
        gambs = a;        
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        lbAgendar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbNotificacao1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        tbTitulo = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        lbTema = new javax.swing.JLabel();
        tbTema = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        lbTurma = new javax.swing.JLabel();
        tbTurma = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        lbData = new javax.swing.JLabel();
        tbData = new com.toedter.calendar.JDateChooser();
        jPanel7 = new javax.swing.JPanel();
        lbObs = new javax.swing.JLabel();
        tbObs = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        lbAluno = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ltAluno = new javax.swing.JList();
        btSelecionaAluno = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        lbArquivo = new javax.swing.JLabel();
        tbArquivo = new javax.swing.JTextField();
        btSelecionaArquivo = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        lbStatus = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        btAgendar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(11, 3));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbAgendar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbAgendar.setText("Agendar Recomendações");
        jPanel1.add(lbAgendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        getContentPane().add(jPanel1);

        lbNotificacao1.setText("Campos com (*) são obrigatórios.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lbNotificacao1)
                .addContainerGap(230, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 26, Short.MAX_VALUE)
                .addComponent(lbNotificacao1))
        );

        getContentPane().add(jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTitulo.setText("Titulo (*):");
        jPanel3.add(lbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        tbTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbTituloActionPerformed(evt);
            }
        });
        jPanel3.add(tbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 210, -1));

        getContentPane().add(jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTema.setText("Tema (*):");
        jPanel4.add(lbTema, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        tbTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbTemaActionPerformed(evt);
            }
        });
        jPanel4.add(tbTema, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 210, -1));

        getContentPane().add(jPanel4);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTurma.setText("Turma(*):");
        jPanel5.add(lbTurma, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));
        jPanel5.add(tbTurma, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 210, -1));

        getContentPane().add(jPanel5);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbData.setText("Data (*):");
        jPanel6.add(lbData, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));
        jPanel6.add(tbData, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 230, -1));

        getContentPane().add(jPanel6);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbObs.setText("Obs.: ");
        lbObs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbObsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbObsMouseExited(evt);
            }
        });
        jPanel7.add(lbObs, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        tbObs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbObsActionPerformed(evt);
            }
        });
        jPanel7.add(tbObs, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 210, -1));

        getContentPane().add(jPanel7);

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbAluno.setText("Aluno(s) (*):");
        jPanel8.add(lbAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        ltAluno.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Adicione alunos aqui.." };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        ltAluno.setSelectedIndex(0);
        ltAluno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ltAlunoFocusLost(evt);
            }
        });
        jScrollPane2.setViewportView(ltAluno);

        jPanel8.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 210, 30));

        btSelecionaAluno.setText("Selecionar");
        btSelecionaAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btSelecionaAlunoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btSelecionaAlunoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btSelecionaAlunoMouseExited(evt);
            }
        });
        btSelecionaAluno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btSelecionaAlunoFocusLost(evt);
            }
        });
        jPanel8.add(btSelecionaAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, -1, -1));

        getContentPane().add(jPanel8);

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbArquivo.setText("Arquivo (*):");
        jPanel9.add(lbArquivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        tbArquivo.setEditable(false);
        tbArquivo.setText("Adicione um arquivo...");
        tbArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbArquivoActionPerformed(evt);
            }
        });
        tbArquivo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tbArquivoFocusLost(evt);
            }
        });
        jPanel9.add(tbArquivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 210, -1));

        btSelecionaArquivo.setText("Selecionar");
        btSelecionaArquivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btSelecionaArquivoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btSelecionaArquivoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btSelecionaArquivoMouseExited(evt);
            }
        });
        btSelecionaArquivo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btSelecionaArquivoFocusLost(evt);
            }
        });
        jPanel9.add(btSelecionaArquivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        getContentPane().add(jPanel9);

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbStatus.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel10.add(lbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        getContentPane().add(jPanel10);

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btAgendar.setText("Agendar");
        btAgendar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAgendarMouseClicked(evt);
            }
        });
        jPanel11.add(btAgendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });
        jPanel11.add(btCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        getContentPane().add(jPanel11);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbTemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbTemaActionPerformed

    private void tbTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbTituloActionPerformed

    private void tbArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbArquivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbArquivoActionPerformed

    private void btSelecionaAlunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSelecionaAlunoMouseClicked
        frag = true;
        TelaSelecionarAluno aluno = new TelaSelecionarAluno();
        aluno.setVisible(true);
    }//GEN-LAST:event_btSelecionaAlunoMouseClicked

    private void btSelecionaArquivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSelecionaArquivoMouseClicked
        TelaSelecionarObj obj = new TelaSelecionarObj();
        obj.setVisible(true);
    }//GEN-LAST:event_btSelecionaArquivoMouseClicked

    private void btAgendarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAgendarMouseClicked
        // TODO add your handling code here:
    
        
        f = new ObjRecomendacao();
        f.setTitulo(tbTitulo.getText());
        f.setTema(tbTema.getText());
        f.setTurma(tbTurma.getText());
        Date d =  new Date();
        DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        d = tbData.getDate();   
        if(d == null){
            f.setDataAgenda("");
        }else{
            f.setDataAgenda(df.format(d));  
        }
        f.setObservacao(tbObs.getText());
        if(frag != false){
            String a = ltAluno.getSelectedValue().toString();
            f.setAluno(a);            
        }
        f.setObjAprendizagem(tbArquivo.getText());        
        
        if(f.getTitulo().equals("") || f.getTema().equals("") || f.getDataAgenda().equals("") || f.getTurma().equals("") || f.getAluno().equals("")
                || f.getObjAprendizagem().equals("")){
            JOptionPane.showMessageDialog(null, "Titulo, Tema, Data, Turma, Aluno ou Objeto estão nulos. Preencha, por favor.");
        }else{            
            JOptionPane.showMessageDialog(null, "Agendamento realizado com sucesso");
            ConexaoBD rs = new ConexaoBD();
            try {
                rs.insereRecomendacao(f.getTitulo(), f.getTema(), f.getDataAgenda(),f.getAluno(),f.getObjAprendizagem(), f.getTurma());
            } catch (SQLException ex) {
                Logger.getLogger(TelaAgendar.class.getName()).log(Level.SEVERE, null, ex);
            }
            f.setObservacao("");
            f.setTema("");
            f.setTitulo("");
            f.setDataAgenda("");
            f.setObjAprendizagem("");
            f.setTurma("");
            tbTitulo.setText("");
            tbTema.setText("");
            tbData.setDate(null);
            tbObs.setText("");
            tbTurma.setText("");
            tbArquivo.setText("Adicione um arquivo a recomendar");
            ltAluno.setModel(new DefaultListModel());
             //APAGAR TODOS OS ITEMS da tabela temp aqui
            try{
                    ConexaoBD.getInstance().deleteTemp();
                    ConexaoBD.getInstance().deleteTempObj();
                }catch(SQLException sqle){
                    Logger.getLogger(TelaSelecionarObj.class.getName()).log(Level.SEVERE, null, sqle);

            }
        }
       
           
        
        
        
    }//GEN-LAST:event_btAgendarMouseClicked

    private void tbObsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbObsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbObsActionPerformed

    private void ltAlunoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ltAlunoFocusLost
        // TODO add your handling code here: 
    }//GEN-LAST:event_ltAlunoFocusLost

    private void btSelecionaAlunoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btSelecionaAlunoFocusLost
        // TODO add your handling code here:
         try{
            alunos = ConexaoBD.getInstance().buscaTempAlunos();            
            for(Aluno a : alunos){
                model.addElement(a.getNome());                
            }                        
            ltAluno.setModel(model);            
        }catch(SQLException sqle){
            Logger.getLogger(TelaSelecionarObj.class.getName()).log(Level.SEVERE, null, sqle);
        } 
    }//GEN-LAST:event_btSelecionaAlunoFocusLost

    private void tbArquivoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tbArquivoFocusLost
       
    }//GEN-LAST:event_tbArquivoFocusLost

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btSelecionaArquivoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btSelecionaArquivoFocusLost
        try{
            objetos = ConexaoBD.getInstance().buscaTempObjetos();            
            for(ObjRecomendacao o: objetos){                
                tbArquivo.setText(o.getTitulo());
            }
            
        }catch(SQLException sqle){
            Logger.getLogger(TelaSelecionarObj.class.getName()).log(Level.SEVERE, null, sqle);
        }
    }//GEN-LAST:event_btSelecionaArquivoFocusLost

    private void btSelecionaAlunoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSelecionaAlunoMouseEntered
        lbStatus.setText("Clique para selecionar os alunos");
        // TODO add your handling code here:
    }//GEN-LAST:event_btSelecionaAlunoMouseEntered

    private void btSelecionaAlunoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSelecionaAlunoMouseExited
        lbStatus.setText("");
    }//GEN-LAST:event_btSelecionaAlunoMouseExited

    private void btSelecionaArquivoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSelecionaArquivoMouseEntered
        // TODO add your handling code here:
        lbStatus.setText("Clique para selecionar o Objeto de Aprendizagem");
    }//GEN-LAST:event_btSelecionaArquivoMouseEntered

    private void btSelecionaArquivoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSelecionaArquivoMouseExited
            // TODO add your handling code here:
        lbStatus.setText("");
    }//GEN-LAST:event_btSelecionaArquivoMouseExited

    private void lbObsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbObsMouseEntered
        // TODO add your handling code here:
      lbStatus.setText("Coloque aqui alguma observação relevante");

    }//GEN-LAST:event_lbObsMouseEntered

    private void lbObsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbObsMouseExited
        // TODO add your handling code here:
        lbStatus.setText("");
    }//GEN-LAST:event_lbObsMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAgendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAgendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAgendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAgendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TelaAgendar().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAgendar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btSelecionaAluno;
    private javax.swing.JButton btSelecionaArquivo;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbAgendar;
    private javax.swing.JLabel lbAluno;
    private javax.swing.JLabel lbArquivo;
    private javax.swing.JLabel lbData;
    private javax.swing.JLabel lbNotificacao1;
    private javax.swing.JLabel lbObs;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JLabel lbTema;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lbTurma;
    public javax.swing.JList ltAluno;
    private javax.swing.JTextField tbArquivo;
    private com.toedter.calendar.JDateChooser tbData;
    private javax.swing.JTextField tbObs;
    private javax.swing.JTextField tbTema;
    private javax.swing.JTextField tbTitulo;
    private javax.swing.JTextField tbTurma;
    // End of variables declaration//GEN-END:variables
  
}
