/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package agendamentorecomendacoes;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author user
 */
public class TelaSelecionarAluno extends javax.swing.JFrame {

    private DefaultListModel model = new DefaultListModel();
    private DefaultListModel model1 = new DefaultListModel();
    private ArrayList<Aluno> alunos;
    /**
     * Creates new form telaSelecionarAluno
     */
    public TelaSelecionarAluno() {
        initComponents();
        setLocationRelativeTo( null );
        try{
            alunos = ConexaoBD.getInstance().buscaAlunos();            
            for(Aluno a : alunos){
                model.addElement(a.getNome());                
            }                        
            mdAlunoListado.setModel(model);            
        }catch(SQLException sqle){
            Logger.getLogger(TelaSelecionarObj.class.getName()).log(Level.SEVERE, null, sqle);
        }        
        
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbBuscarAlunos = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mdAlunoListado = new javax.swing.JList();
        btAddAluno = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        mdAlunoSelecionado = new javax.swing.JList();
        btRemAluno = new javax.swing.JButton();
        lbAlunoSelecionado = new javax.swing.JLabel();
        lbAlunoListado = new javax.swing.JLabel();
        btConcluir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbBuscarAlunos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbBuscarAlunos.setText("Buscar Alunos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(lbBuscarAlunos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbBuscarAlunos)
                .addContainerGap())
        );

        mdAlunoListado.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        mdAlunoListado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mdAlunoListadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(mdAlunoListado);

        btAddAluno.setText(">>");
        btAddAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAddAlunoMouseClicked(evt);
            }
        });

        jScrollPane2.setViewportView(mdAlunoSelecionado);

        btRemAluno.setText("<<");
        btRemAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btRemAlunoMouseClicked(evt);
            }
        });
        btRemAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemAlunoActionPerformed(evt);
            }
        });

        lbAlunoSelecionado.setText("Alunos Selecionados");

        lbAlunoListado.setText("Alunos Listados");

        btConcluir.setText("Concluir");
        btConcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btConcluirMouseClicked(evt);
            }
        });
        btConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(btConcluir))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btAddAluno)
                                    .addComponent(btRemAluno)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(lbAlunoListado)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lbAlunoSelecionado)
                                .addGap(35, 35, 35)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAlunoSelecionado)
                    .addComponent(lbAlunoListado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btAddAluno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btRemAluno)
                        .addGap(52, 52, 52)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btConcluir))
        );

        jLabel1.setText("Clique no nome de um aluno e depois em >> para selecionar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(58, 58, 58))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRemAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btRemAlunoActionPerformed

    private void btConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConcluirActionPerformed
    }//GEN-LAST:event_btConcluirActionPerformed

    private void btAddAlunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAddAlunoMouseClicked
        // TODO add your handling code here:       
        model1.addElement(mdAlunoListado.getSelectedValue());
        mdAlunoSelecionado.setModel(model1);      
        model.remove(mdAlunoListado.getSelectedIndex());
        mdAlunoListado.setModel(model);
    }//GEN-LAST:event_btAddAlunoMouseClicked

    private void mdAlunoListadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mdAlunoListadoMouseClicked
        // TODO add your handling code here:        
    }//GEN-LAST:event_mdAlunoListadoMouseClicked

    private void btRemAlunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRemAlunoMouseClicked
        // TODO add your handling code here:
        model.addElement(mdAlunoSelecionado.getSelectedValue());
        mdAlunoListado.setModel(model);      
        model1.remove(mdAlunoSelecionado.getSelectedIndex());
        mdAlunoSelecionado.setModel(model1);        
    }//GEN-LAST:event_btRemAlunoMouseClicked

    private void btConcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btConcluirMouseClicked
        // TODO add your handling code here:        
        for(int i=0;i<model1.getSize();i++){
           String nome = model1.getElementAt(i).toString();
           try {
                ConexaoBD.getInstance().insereTemp(nome);
           } catch (SQLException ex) {
                Logger.getLogger(TelaSelecionarAluno.class.getName()).log(Level.SEVERE, null, ex);
           }
        }
        this.dispose();
    }//GEN-LAST:event_btConcluirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSelecionarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSelecionarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSelecionarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSelecionarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TelaSelecionarAluno().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddAluno;
    private javax.swing.JButton btConcluir;
    private javax.swing.JButton btRemAluno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbAlunoListado;
    private javax.swing.JLabel lbAlunoSelecionado;
    private javax.swing.JLabel lbBuscarAlunos;
    private javax.swing.JList mdAlunoListado;
    private javax.swing.JList mdAlunoSelecionado;
    // End of variables declaration//GEN-END:variables
}
