/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package agendamentorecomendacoes;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class TelaGerenciar extends javax.swing.JFrame {

    /**
     * Creates new form TelaGerenciar
     */
    private ArrayList<String> titulos = new ArrayList<String>();
    private ArrayList<String> tema = new ArrayList<String>();
    private ArrayList<String> data = new ArrayList<String>();
    private ArrayList<Aluno> aluno = new ArrayList<Aluno>();
    private ArrayList<ObjRecomendacao> obj = new ArrayList<ObjRecomendacao>();

    
    public TelaGerenciar() throws SQLException {
        initComponents();
        ConexaoBD cn = new ConexaoBD();
        cn.removeRecomendacaoAntiga();
        setLocationRelativeTo( null );
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbHistorico = new javax.swing.JLabel();
        lbDescricao = new javax.swing.JLabel();
        lbCampo = new javax.swing.JLabel();
        cbCampo = new javax.swing.JComboBox();
        lbBusca = new javax.swing.JLabel();
        tbBusca = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlResultado = new javax.swing.JList();
        lbResultado = new javax.swing.JLabel();
        btEditar = new javax.swing.JButton();
        btBuscar = new javax.swing.JButton();
        lbStatus = new javax.swing.JLabel();
        btRemover = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbHistorico.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbHistorico.setText("Gerenciar Histórico");
        getContentPane().add(lbHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 20));

        lbDescricao.setText("Gerencie as recomendações já feitas aqui.  Selecione um campo para a busca. ");
        getContentPane().add(lbDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        lbCampo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbCampo.setText("Campo:");
        getContentPane().add(lbCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        cbCampo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Titulo", "Tema", "Turma", "Aluno", "Data" }));
        getContentPane().add(cbCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        lbBusca.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbBusca.setText("Busca:");
        getContentPane().add(lbBusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        tbBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbBuscaKeyPressed(evt);
            }
        });
        getContentPane().add(tbBusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 130, -1));

        jScrollPane1.setViewportView(jlResultado);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 370, 140));

        lbResultado.setText("Resultado da Busca:");
        getContentPane().add(lbResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        btEditar.setText("Editar");
        btEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btEditarMouseClicked(evt);
            }
        });
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 90, -1));

        btBuscar.setText("Buscar");
        btBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btBuscarMouseClicked(evt);
            }
        });
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, -1, -1));

        lbStatus.setText("Será disposto por título, tema, aluno, turma, objeto  e data");
        getContentPane().add(lbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 440, -1));

        btRemover.setText("Remover");
        btRemover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btRemoverMouseClicked(evt);
            }
        });
        getContentPane().add(btRemover, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 90, -1));

        btCancelar.setText("Cancelar");
        btCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCancelarMouseClicked(evt);
            }
        });
        getContentPane().add(btCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 310, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed

    }//GEN-LAST:event_btEditarActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btBuscarActionPerformed

    private void tbBuscaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbBuscaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbBuscaKeyPressed

    private void btBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btBuscarMouseClicked
        // TODO add your handling code here:
        String busca = tbBusca.getText();        
        String tipoBusca = cbCampo.getSelectedItem().toString();
        
        if(tipoBusca.equals("Titulo")){
            try {
                obj = ConexaoBD.getInstance().buscaPorTitulo(busca);
                DefaultListModel model = new DefaultListModel();
                String tudo;
                int i = 1;
                for(ObjRecomendacao o : obj){
                    tudo = i +") " + o.getTitulo() + " | "+ o.getTema() + " | "+ o.getAluno() + " | "+ o.getObservacao() + " | "+ o.getObjAprendizagem() + " | "+ o.getDataAgenda();
                    model.addElement(tudo);
                    i++;
                }
                if (i < 2){
                    tudo = "Sem resultados";
                    model.addElement(tudo);
                }
                jlResultado.setModel(model);
            } catch (SQLException ex) {
                Logger.getLogger(TelaGerenciar.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if(tipoBusca.equals("Tema")){
            try {
                obj = ConexaoBD.getInstance().buscaPorTema(busca);
                DefaultListModel model = new DefaultListModel();
                String tudo;
                int i = 1;
                for(ObjRecomendacao o : obj){
                    tudo = i +") " + o.getTitulo() + " | "+ o.getTema() + " | "+ o.getAluno() + " | "+ o.getObservacao() + " | "+ o.getObjAprendizagem() + " | "+ o.getDataAgenda();
                    model.addElement(tudo);
                    i++;
                }
                 if (i < 2){
                    tudo = "Sem resultados";
                    model.addElement(tudo);
                }
                jlResultado.setModel(model);
            } catch (SQLException ex) {
                Logger.getLogger(TelaGerenciar.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if(tipoBusca.equals("Turma")){
            try {
                obj = ConexaoBD.getInstance().buscaPorTurma(busca);
                DefaultListModel model = new DefaultListModel();
                String tudo;
                int i = 1;
                for(ObjRecomendacao o : obj){
                    tudo = i +") " + o.getTitulo() + " | "+ o.getTema() + " | "+ o.getAluno() + " | "+ o.getObservacao() + " | "+ o.getObjAprendizagem() + " | "+ o.getDataAgenda();
                    model.addElement(tudo);
                    i++;
                }
                 if (i < 2){
                    tudo = "Sem resultados";
                    model.addElement(tudo);
                }
                jlResultado.setModel(model);
            } catch (SQLException ex) {
                Logger.getLogger(TelaGerenciar.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if(tipoBusca.equals("Aluno")){
            try {
                obj = ConexaoBD.getInstance().buscaPorAluno(busca);
                DefaultListModel model = new DefaultListModel();
                String tudo;
                int i = 1;
                for(ObjRecomendacao o : obj){
                    tudo = i +") " + o.getTitulo() + " | "+ o.getTema() + " | "+ o.getAluno() + " | "+ o.getObservacao() + " | "+ o.getObjAprendizagem() + " | "+ o.getDataAgenda();
                    model.addElement(tudo);
                    i++;
                }
                 if (i < 2){
                    tudo = "Sem resultados";
                    model.addElement(tudo);
                }
                jlResultado.setModel(model);
            } catch (SQLException ex) {
                Logger.getLogger(TelaGerenciar.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if(tipoBusca.equals("Data")){
            try {
                obj = ConexaoBD.getInstance().buscaPorData(busca);
                DefaultListModel model = new DefaultListModel();
                String tudo;
                int i = 1;
                for(ObjRecomendacao o : obj){
                    tudo = i +") " + o.getTitulo() + " | "+ o.getTema() + " | "+ o.getAluno() + " | "+ o.getObservacao() + " | "+ o.getObjAprendizagem() + " | "+ o.getDataAgenda();
                    model.addElement(tudo);
                    i++;
                }
                 if (i < 2){
                    tudo = "Sem resultados";
                    model.addElement(tudo);
                }
                jlResultado.setModel(model);
            } catch (SQLException ex) {
                Logger.getLogger(TelaGerenciar.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_btBuscarMouseClicked

    private void btRemoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRemoverMouseClicked
       int a = jlResultado.getSelectedIndex();
       if(a < 0){
            JOptionPane.showMessageDialog(null, "Selecione uma recomendação para remove-la");   
       }else{
        String rem = jlResultado.getSelectedValue().toString();
        int j = rem.indexOf(" "); /* Busca na string, a posição do ' ' espaço, e retorna o indice dele */ 
        rem = rem.substring(j+1,rem.length()); /* Aqui é separada a String do primeiro caractere até o primeiro espaço*/
        j = rem.indexOf(" "); /* Busca na string, a posição do ' ' espaço, e retorna o indice dele */ 
        rem = rem.substring(0,j); /* Aqui é separada a String do primeiro caractere até o primeiro espaço*/
        int decisao = JOptionPane.showConfirmDialog(null, "Deseja remover?");      
        if(decisao == 0){
            try {
                    ConexaoBD.getInstance().deleteRecomendacao(rem);
                    JOptionPane.showMessageDialog(null, "Recomendação removida com sucesso");
                    String busca = tbBusca.getText();  
                    String tipoBusca = cbCampo.getSelectedItem().toString();
                    if(tipoBusca.equals("Titulo")){
                try {

                    obj = ConexaoBD.getInstance().buscaPorTitulo(busca);
                    DefaultListModel model = new DefaultListModel();
                    String tudo;
                    int i = 1;
                    for(ObjRecomendacao o : obj){
                        tudo = i +") " + o.getTitulo() + " | "+ o.getTema() + " | "+ o.getAluno() + " | "+ o.getObservacao() + " | "+ o.getObjAprendizagem() + " | "+ o.getDataAgenda();
                        model.addElement(tudo);
                        i++;
                    }
                    if (i < 2){
                        tudo = "Sem resultados";
                        model.addElement(tudo);
                    }
                    jlResultado.setModel(model);
                } catch (SQLException ex) {
                    Logger.getLogger(TelaGerenciar.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else if(tipoBusca.equals("Tema")){
                try {
                    obj = ConexaoBD.getInstance().buscaPorTema(busca);
                    DefaultListModel model = new DefaultListModel();
                    String tudo;
                    int i = 1;
                    for(ObjRecomendacao o : obj){
                        tudo = i +") " + o.getTitulo() + " | "+ o.getTema() + " | "+ o.getAluno() + " | "+ o.getObservacao() + " | "+ o.getObjAprendizagem() + " | "+ o.getDataAgenda();
                        model.addElement(tudo);
                        i++;
                    }
                    if (i < 2){
                        tudo = "Sem resultados";
                        model.addElement(tudo);
                    }
                    jlResultado.setModel(model);
                } catch (SQLException ex) {
                    Logger.getLogger(TelaGerenciar.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else if(tipoBusca.equals("Turma")){
                try {
                    obj = ConexaoBD.getInstance().buscaPorTurma(busca);
                    DefaultListModel model = new DefaultListModel();
                    String tudo;
                    int i = 1;
                    for(ObjRecomendacao o : obj){
                        tudo = i +") " + o.getTitulo() + " | "+ o.getTema() + " | "+ o.getAluno() + " | "+ o.getObservacao() + " | "+ o.getObjAprendizagem() + " | "+ o.getDataAgenda();
                        model.addElement(tudo);
                        i++;
                    }
                    if (i < 2){
                        tudo = "Sem resultados";
                        model.addElement(tudo);
                    }
                    jlResultado.setModel(model);
                } catch (SQLException ex) {
                    Logger.getLogger(TelaGerenciar.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else if(tipoBusca.equals("Aluno")){
                try {
                    obj = ConexaoBD.getInstance().buscaPorAluno(busca);
                    DefaultListModel model = new DefaultListModel();
                    String tudo;
                    int i = 1;
                    for(ObjRecomendacao o : obj){
                        tudo = i +") " + o.getTitulo() + " | "+ o.getTema() + " | "+ o.getAluno() + " | "+ o.getObservacao() + " | "+ o.getObjAprendizagem() + " | "+ o.getDataAgenda();
                        model.addElement(tudo);
                        i++;
                    }
                    if (i < 2){
                        tudo = "Sem resultados";
                        model.addElement(tudo);
                    }
                    jlResultado.setModel(model);
                } catch (SQLException ex) {
                    Logger.getLogger(TelaGerenciar.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else if(tipoBusca.equals("Data")){
                try {
                    obj = ConexaoBD.getInstance().buscaPorData(busca);
                    DefaultListModel model = new DefaultListModel();
                    String tudo;
                    int i = 1;
                    for(ObjRecomendacao o : obj){
                        tudo = i +") " + o.getTitulo() + " | "+ o.getTema() + " | "+ o.getAluno() + " | "+ o.getObservacao() + " | "+ o.getObjAprendizagem() + " | "+ o.getDataAgenda();
                        model.addElement(tudo);
                        i++;
                    }
                    if (i < 2){
                        tudo = "Sem resultados";
                        model.addElement(tudo);
                    }
                    jlResultado.setModel(model);
                } catch (SQLException ex) {
                    Logger.getLogger(TelaGerenciar.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
                } catch (SQLException ex) {
                    Logger.getLogger(TelaGerenciar.class.getName()).log(Level.SEVERE, null, ex);
                }
        }
       }
         
    }//GEN-LAST:event_btRemoverMouseClicked

    private void btEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btEditarMouseClicked
        // TODO add your handling code here:
        int a = jlResultado.getSelectedIndex();
        if(a < 0){
         JOptionPane.showMessageDialog(null, "Selecione uma recomendação para edita-la");   
        }else{
            String titulo = jlResultado.getSelectedValue().toString();
            int j = titulo.indexOf(")"); /* Busca na string, a posição do ' ' espaço, e retorna o indice dele */ 
            titulo = titulo.substring(j+1,titulo.length()); /* Aqui é separada a String do primeiro caractere até o primeiro espaço*/
            j = titulo.indexOf("|"); /* Busca na string, a posição do ' ' espaço, e retorna o indice dele */ 
            titulo = titulo.substring(1,j-1); /* Aqui é separada a String do primeiro caractere até o primeiro espaço*/            
            
            String tema = jlResultado.getSelectedValue().toString();
            j = tema.indexOf("|"); /* Busca na string, a posição do ' ' espaço, e retorna o indice dele */ 
            tema = tema.substring(j+1,tema.length()); /* Aqui é separada a String do primeiro caractere até o primeiro espaço*/
            j = tema.indexOf("|"); /* Busca na string, a posição do ' ' espaço, e retorna o indice dele */ 
            tema = tema.substring(1,j-1); /* Aqui é separada a String do primeiro caractere até o primeiro espaço*/           
            
            String aluno = jlResultado.getSelectedValue().toString();
            j = aluno.indexOf("|"); /* Busca na string, a posição do ' ' espaço, e retorna o indice dele */ 
            aluno = aluno.substring(j+1,aluno.length()); /* Aqui é separada a String do primeiro caractere até o primeiro espaço*/
            j = aluno.indexOf("|"); /* Busca na string, a posição do ' ' espaço, e retorna o indice dele */ 
            aluno = aluno.substring(j+1,aluno.length()); /* Aqui é separada a String do primeiro caractere até o primeiro espaço*/            
            j = aluno.indexOf("|"); /* Busca na string, a posição do ' ' espaço, e retorna o indice dele */ 
            aluno = aluno.substring(1,j-1); /* Aqui é separada a String do primeiro caractere até o primeiro espaço*/            
            
            String turma = jlResultado.getSelectedValue().toString();
            j = turma.indexOf("|"); /* Busca na string, a posição do ' ' espaço, e retorna o indice dele */ 
            turma = turma.substring(j+1,turma.length()); /* Aqui é separada a String do primeiro caractere até o primeiro espaço*/
            j = turma.indexOf("|"); /* Busca na string, a posição do ' ' espaço, e retorna o indice dele */ 
            turma = turma.substring(j+1,turma.length()); /* Aqui é separada a String do primeiro caractere até o primeiro espaço*/            
            j = turma.indexOf("|"); /* Busca na string, a posição do ' ' espaço, e retorna o indice dele */ 
            turma = turma.substring(j+1,turma.length()); /* Aqui é separada a String do primeiro caractere até o primeiro espaço*/            
            j = turma.indexOf("|"); /* Busca na string, a posição do ' ' espaço, e retorna o indice dele */ 
            turma = turma.substring(1,j-1); /* Aqui é separada a String do primeiro caractere até o primeiro espaço*/                        
            
            String obj = jlResultado.getSelectedValue().toString();
            j = obj.indexOf("|"); /* Busca na string, a posição do ' ' espaço, e retorna o indice dele */ 
            obj = obj.substring(j+1,obj.length()); /* Aqui é separada a String do primeiro caractere até o primeiro espaço*/
            j = obj.indexOf("|"); /* Busca na string, a posição do ' ' espaço, e retorna o indice dele */ 
            obj = obj.substring(j+1,obj.length()); /* Aqui é separada a String do primeiro caractere até o primeiro espaço*/            
            j = obj.indexOf("|"); /* Busca na string, a posição do ' ' espaço, e retorna o indice dele */ 
            obj = obj.substring(j+1,obj.length()); /* Aqui é separada a String do primeiro caractere até o primeiro espaço*/            
            j = obj.indexOf("|"); /* Busca na string, a posição do ' ' espaço, e retorna o indice dele */ 
            obj = obj.substring(j+1,obj.length()); /* Aqui é separada a String do primeiro caractere até o primeiro espaço*/            
            j = obj.indexOf("|"); /* Busca na string, a posição do ' ' espaço, e retorna o indice dele */ 
            obj = obj.substring(1,j-1); /* Aqui é separada a String do primeiro caractere até o primeiro espaço*/                           
            
            String data = jlResultado.getSelectedValue().toString();
            j = data.indexOf("|"); /* Busca na string, a posição do ' ' espaço, e retorna o indice dele */ 
            data = data.substring(j+1,data.length()); /* Aqui é separada a String do primeiro caractere até o primeiro espaço*/
            j = data.indexOf("|"); /* Busca na string, a posição do ' ' espaço, e retorna o indice dele */ 
            data = data.substring(j+1,data.length()); /* Aqui é separada a String do primeiro caractere até o primeiro espaço*/            
            j = data.indexOf("|"); /* Busca na string, a posição do ' ' espaço, e retorna o indice dele */ 
            data = data.substring(j+1,data.length()); /* Aqui é separada a String do primeiro caractere até o primeiro espaço*/            
            j = data.indexOf("|"); /* Busca na string, a posição do ' ' espaço, e retorna o indice dele */ 
            data = data.substring(j+1,data.length()); /* Aqui é separada a String do primeiro caractere até o primeiro espaço*/            
            j = data.indexOf("|"); /* Busca na string, a posição do ' ' espaço, e retorna o indice dele */ 
            data = data.substring(j+1,data.length()); /* Aqui é separada a String do primeiro caractere até o primeiro espaço*/            
            j = 11;
            data = data.substring(1,j); /* Aqui é separada a String do primeiro caractere até o primeiro espaço*/                           
            
            ObjRecomendacao objEdita = new ObjRecomendacao(titulo, tema, aluno, turma, obj, data);            
            TelaEditar editar = new TelaEditar(objEdita);            
            editar.setVisible(true);
        }
    }//GEN-LAST:event_btEditarMouseClicked

    private void btCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCancelarMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btCancelarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
                    new TelaGerenciar().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(TelaGerenciar.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btRemover;
    private javax.swing.JComboBox cbCampo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList jlResultado;
    private javax.swing.JLabel lbBusca;
    private javax.swing.JLabel lbCampo;
    private javax.swing.JLabel lbDescricao;
    private javax.swing.JLabel lbHistorico;
    private javax.swing.JLabel lbResultado;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JTextField tbBusca;
    // End of variables declaration//GEN-END:variables
}
